# Generated by Django 4.2.8 on 2025-05-07 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('codefusionapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=128)),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('capital', models.CharField(blank=True, max_length=128)),
                ('population', models.BigIntegerField()),
                ('region', models.CharField(max_length=64)),
                ('timezones', models.JSONField()),
                ('flag', models.URLField()),
                ('languages', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.DeleteModel(
            name='Note',
        ),
    ]
